### ISSUE TITLE
Functionality to skip specific files if needed.

### ISSUE THREAD

**Issue by pamelaeteng26** [aws-samples/lza-validator#4]
**Description:**
I am proposing a new feature for the LZA Validator tool to allow users to specify files or patterns of files to be skipped during the validation process. Currently, the tool validates all files within the specified directories, which can lead to issues when certain files are not intended for validation or are known to not comply with the LZA's validation rules but are still required.

**Background:**
In our use case, we have specific configuration files that require certain permissions which would rather not give. The current behaviour of validating all files without an option to exclude them results in validation failures that are not actually indicative of a problem with our Landing Zone configuration.

**Expected Behaviour:**
I would like the LZA Validator to support an option, where users can specify files or patterns to be excluded from validation. This would allow for greater flexibility and prevent unnecessary validation errors.

**Conclusion**
Allowing file exclusions would enhance the usability of the LZA Validator.

**Comment by jc1518** [comment]
Hi @pamelaeteng26 , it can be done while mounting the volume into the docker container. For example, if you would like to exclude a file named `test.yaml`, then you need to add `--volume /dev/null:/lza/config/test.yaml`.

**Comment by pamelaeteng26** [comment]
Thank you
